const { initializeApp } = require('firebase/app');
const { getFirestore, collection, setDoc, doc } = require('firebase/firestore');

// Firebase configuration
const firebaseConfig = {
    
};

// Initialize Firebase
const firebaseApp = initializeApp(firebaseConfig);
const db = getFirestore(firebaseApp);

// Data for FoodItems and their calories
const foodItems = [
    { "itemName": "Idly", "calories": 40 },
    { "itemName": "Vada", "calories": 150 },
    { "itemName": "Sambar", "calories": 70 },
    { "itemName": "Chutney", "calories": 50 },
    { "itemName": "R. Kichadi", "calories": 160 },
    { "itemName": "B.B.J (Bread Butter Jam)", "calories": 150 },
    { "itemName": "Tea", "calories": 30 },
    { "itemName": "Coffee", "calories": 40 },
    { "itemName": "Milk", "calories": 100 },
    { "itemName": "Masala Dosa", "calories": 210 },
    { "itemName": "Aloo Paratha", "calories": 180 },
    { "itemName": "Pickle", "calories": 20 },
    { "itemName": "Pongal", "calories": 200 },
    { "itemName": "Coconut Chutney", "calories": 80 },
    { "itemName": "Poori", "calories": 150 },
    { "itemName": "Aloo Masala", "calories": 100 },
    { "itemName": "Gobi Paratha", "calories": 170 },
    { "itemName": "Scrambled Egg", "calories": 140 },
    { "itemName": "Bread Toast", "calories": 100 },
    { "itemName": "Cornflakes", "calories": 100 },
    { "itemName": "Boiled Egg", "calories": 70 },
    { "itemName": "French Toast", "calories": 220 },
    { "itemName": "Kal Dosa", "calories": 130 },
    { "itemName": "Vadacurry", "calories": 180 },
    { "itemName": "Pav Bhaji Masala", "calories": 250 },
    { "itemName": "Veg Puff", "calories": 180 },
    { "itemName": "Veg Sandwich", "calories": 150 },
    { "itemName": "Cheese Toast", "calories": 200 },
    { "itemName": "Upma", "calories": 160 },
    { "itemName": "Poha", "calories": 150 },
    { "itemName": "Semiya", "calories": 150 },
    { "itemName": "Kitchadi", "calories": 160 },
    { "itemName": "Fried Egg", "calories": 90 },
    { "itemName": "Rava Dosa", "calories": 100 },
    { "itemName": "Onion Pakoda", "calories": 180 },
    { "itemName": "Veg Cutlet", "calories": 180 },
    { "itemName": "Samosa", "calories": 120 },
    { "itemName": "Dahi Vada", "calories": 150 },
    { "itemName": "Mysore Masala Dosa", "calories": 220 },
    { "itemName": "Egg Burji", "calories": 160 },
    { "itemName": "Podi Idly", "calories": 60 },
    { "itemName": "Masala Poori", "calories": 200 },
    { "itemName": "Masala Omelette", "calories": 150 },
    { "itemName": "Phulka", "calories": 80 },
    { "itemName": "Dal Fry", "calories": 150 },
    { "itemName": "Paneer Masala", "calories": 220 },
    { "itemName": "Paneer Do Pyaza", "calories": 230 },
    { "itemName": "Paneer Butter Masala", "calories": 300 },
    { "itemName": "White Rice", "calories": 200 },
    { "itemName": "Sambar", "calories": 70 },
    { "itemName": "Rasam", "calories": 60 },
    { "itemName": "Jeera Rice", "calories": 200 },
    { "itemName": "Lemon Rice", "calories": 180 },
    { "itemName": "Thuvayal", "calories": 50 },
    { "itemName": "Soya Chunks Masala", "calories": 180 },
    { "itemName": "Chole Punjabi", "calories": 240 },
    { "itemName": "Curd", "calories": 60 },
    { "itemName": "Fryums", "calories": 50 },
    { "itemName": "Variety Rice", "calories": 200 },
    { "itemName": "Ghee Phulka", "calories": 100 },
    { "itemName": "Paneer Bhurji", "calories": 180 },
    { "itemName": "Dal Tadka", "calories": 150 },
    { "itemName": "Mixed Veg Curry", "calories": 160 },
    { "itemName": "Dal Rajma", "calories": 160 },
    { "itemName": "Paneer Kofta", "calories": 260 },
    { "itemName": "Veg Salad", "calories": 50 },
    { "itemName": "Paneer Makhanwala", "calories": 300 },
    { "itemName": "Paneer Palak Masala", "calories": 220 },
    { "itemName": "Keerai Koottu", "calories": 120 },
    { "itemName": "Paneer Tikka", "calories": 250 },
    { "itemName": "Maharani Rice", "calories": 220 },
    { "itemName": "Maharashtrian White Rice", "calories": 200 },
    { "itemName": "Gobi Manchurian", "calories": 230 },
    { "itemName": "Schezwan Veg Fried Rice", "calories": 240 },
    { "itemName": "Paneer Kurma", "calories": 270 },
    { "itemName": "Veg Korma", "calories": 240 },
    { "itemName": "Veg Pulao", "calories": 240 },
    { "itemName": "Veg Biryani", "calories": 320 },
    { "itemName": "Veg Fried Rice", "calories": 240 },
    { "itemName": "Rajma Masala", "calories": 160 },
    { "itemName": "Butter Naan", "calories": 200 },
    { "itemName": "Kadai Chicken", "calories": 280 },
    { "itemName": "Chicken Biryani", "calories": 320 },
    { "itemName": "Chicken Curry", "calories": 270 },
    { "itemName": "Chicken 65", "calories": 300 },
    { "itemName": "Chicken Tikka Masala", "calories": 320 },
    { "itemName": "Chicken Do Piazha", "calories": 300 },
    { "itemName": "Tomato Kuzhambu", "calories": 150 },
    { "itemName": "Paneer Makhani", "calories": 330 },
    { "itemName": "Soya Chunks", "calories": 160 },
    { "itemName": "Dhal Vada", "calories": 150 },
    { "itemName": "Dal Maharani", "calories": 220 },
    { "itemName": "Kara Kozhambhu", "calories": 200 },
    { "itemName": "Dahi Vada", "calories": 150 },
    { "itemName": "Oil Brinjal", "calories": 130 },
    { "itemName": "Poriyal", "calories": 100 },
    { "itemName": "Dal Panchmel", "calories": 180 },
    { "itemName": "Methi Chapathi", "calories": 80 },
    { "itemName": "Veg Kuftha Curry", "calories": 220 },
    { "itemName": "Tandoori Paneer", "calories": 250 },
    { "itemName": "Paneer Kofta", "calories": 260 },
    { "itemName": "Aloo Gobi", "calories": 190 },
    { "itemName": "Bindi Masala", "calories": 150 },
    { "itemName": "Dry Biscuits", "calories": 50 },
    { "itemName": "Bhaji", "calories": 180 },
    { "itemName": "Masala Puri", "calories": 200 },
    { "itemName": "Vada Pav", "calories": 300 },
    { "itemName": "Croquette Potato", "calories": 180 },
    { "itemName": "Stuffed Bread Roll", "calories": 150 },
    { "itemName": "Eggless Cake", "calories": 120 },
    { "itemName": "Onion Bajji", "calories": 180 },
    { "itemName": "Raw Banana Bhaji", "calories": 150 },
    { "itemName": "Bread Roll", "calories": 150 },
    { "itemName": "Badam Halwa", "calories": 250 },
    { "itemName": "Cutlet", "calories": 180 },
    { "itemName": "Pizza", "calories": 300 },
    { "itemName": "Spring Rolls", "calories": 150 },
    { "itemName": "Dahi Papdi Chat", "calories": 200 },
    { "itemName": "Cream Cake", "calories": 120 },
    { "itemName": "Onion Rings", "calories": 180 },
    { "itemName": "Masala Papad", "calories": 40 },
    { "itemName": "Veg Spring Roll", "calories": 150 },
    { "itemName": "Chips", "calories": 150 },
    { "itemName": "Channa Chat", "calories": 180 },
    { "itemName": "Pani Poori", "calories": 100 },
    { "itemName": "Veg Puffs", "calories": 180 },
    { "itemName": "Croquette", "calories": 180 },
    { "itemName": "Masala Peanuts", "calories": 200 },
    { "itemName": "Mint Chutney", "calories": 20 },
    { "itemName": "Hot Badam Milk", "calories": 250 },
    { "itemName": "Crouquete Potato", "calories": 180 },
    { "itemName": "Vada Paav", "calories": 300 },
    { "itemName": "Biscuits", "calories": 50 },
    { "itemName": "Butter Milk", "calories": 50 },
    { "itemName": "Bananas", "calories": 90 },
    { "itemName": "Mixed Veg Gravy", "calories": 160 },
    { "itemName": "Paneer Curry", "calories": 240 },
    { "itemName": "Dal Makhani", "calories": 220 },
    { "itemName": "Wheel Chips", "calories": 50 },
    { "itemName": "Salad", "calories": 50 },
    { "itemName": "Raita", "calories": 50 },
    { "itemName": "Aloo Brinjal Drumstick Masala", "calories": 180 },
    { "itemName": "Fruit Salad", "calories": 80 },
    { "itemName": "Loose Curd", "calories": 60 },
    { "itemName": "Jeera Rice", "calories": 200 },
    { "itemName": "Aloo Capsicum Masala", "calories": 180 },
    { "itemName": "Schezwan Egg Fried Rice", "calories": 240 },
    { "itemName": "Gobi Rice", "calories": 230 },
    { "itemName": "Dal Lasoni", "calories": 180 },
    { "itemName": "Egg Fried Rice", "calories": 240 },
    { "itemName": "Green Veg Sabzi", "calories": 120 },
    { "itemName": "Tomato Rasam", "calories": 60 },
    { "itemName": "Aloo Baigan", "calories": 150 },
    { "itemName": "Veg Kolhapuri", "calories": 230 },
    { "itemName": "Meal Maker Masala", "calories": 200 },
    { "itemName": "Banana", "calories": 90 },
    { "itemName": "Veg Jal Frizhi", "calories": 200 },
    { "itemName": "Paneer Manchurian", "calories": 230 },
    { "itemName": "Tandoori Paneer", "calories": 250 },
    { "itemName": "Butter Naan", "calories": 200 },
    { "itemName": "Green Poriyal", "calories": 100 }
];

// Seeding function for FoodItems data
const seedFoodItems = async () => {
  for (const foodItem of foodItems) {
    const foodItemDoc = doc(collection(db, 'FoodItem')); // Ensure this matches your collection name in Firestore
    await setDoc(foodItemDoc, foodItem);
    console.log(`Inserted food item: ${foodItem.itemName}`);
  }
  console.log('Food items seeding completed.');
};

// Run the seeding function
seedFoodItems().catch(console.error);
